### ISSUE TITLE
.github config & automation

### ISSUE THREAD

**Issue by msualp** [sociail/.github#1]
# TASKS

- [ ] Create .githubsettings file for all repos
- [ ] Main branch from PROD to main

# TO DO

- [ ] **Workflows (`workflows/`)**: Contains YAML files for GitHub Actions workflows.
- [ ] **Issue Templates (`ISSUE_TEMPLATE/`)**: Folder with templates for issues.
- [ ] **Pull Request Templates (`PULL_REQUEST_TEMPLATE.md`)**: Template for pull requests.
- [ ] **Code Owners (`CODEOWNERS`)**: Specifies repository code owners.
- [ ] **Security Policies (`SECURITY.md`)**: Instructions for reporting security issues.
- [ ] **GitHub Pages Configuration (`.nojekyll`)**: Disables Jekyll processing on GitHub Pages.
- [ ] **Configuration Files (`config.yml`)**: Various configuration files for GitHub Apps and Actions.
- [ ] **Stale Bot Configuration (`stale.yml`)**: Configuration for a bot that marks issues and PRs as stale.
- [ ] **GitHub Dependabot (`dependabot.yml`)**: Configuration for Dependabot for dependency updates.
- [ ] **Proposal Template**
